# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a5f37be775d71463aa973a4d52ec84e7fa02b7caee0e0a9a7389d321128c9c604a1e434d50482bedd56e514e705b2b22558fe2b41798caa7d61fce4494f40f

test:
  secret_key_base: 52839098e4ff40e3f91b01dc9a75cd57d7916ad06f11e22a319b02b1af4e3c416a89e3bdb5faf7ea0e8c374d86f79a90ac8885c28f6837972022b9de975123ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
